BASE_DIRECTORY: C:\projects\Magellon01\CoreService\config
ENV_TYPE: development

DOCKER_URL: tcp://localhost:2375
DOCKER_REPOSITORY: tcp://localhost:2375
DOCKER_USERNAME: khoshbin
DOCKER_PASSWORD: khoshbin

SLACK_TOKEN: xoxb-5284990093169-5258053840439-aJ8x7uHcUCNqCKSZkbOSbAlq


DEBUG_CTF: true
DEBUG_CTF_PATH : C:/magellon/gpfs
DEBUG_CTF_REPLACE : /gpfs


consul_settings:
  CONSUL_HOST: 192.168.92.133
  CONSUL_PASSWORD: '8500'
  CONSUL_PORT: 8500
  CONSUL_SERVICE_ID: magellon-service-11f0bd1e-8c57-412d-82e4-0c940da261c6
  CONSUL_SERVICE_NAME: magellon-core-service
  CONSUL_USERNAME: '8500'

database_settings:
  DB_Driver: mysql+pymysql
  DB_HOST: localhost
  DB_NAME: magellon01
  DB_PASSWORD: behd1d2
  DB_Port: 3306
  DB_USER: root

leginon_db_settings:
  ENABLED: true
  HOST: 127.0.0.1
  PORT: 3310
  USER: usr_object
  PASSWORD: ThPHMn3m39Ds
  DATABASE: dbemdata

api_docs_settings:
  ENABLED: true
  USERNAME: admin
  PASSWORD: admin123

security_setup_settings:
  ENABLED: true
  SETUP_TOKEN: null  # No token required in dev (set to a secret string for extra security)
  AUTO_DISABLE: false  # Don't auto-disable in dev (allow multiple runs for testing)



rabbitmq_settings:
  HOST_NAME: localhost
  PORT: 5672
  USER_NAME: rabbit
  PASSWORD: behd1d2
  VIRTUAL_HOST: /
  SSL_ENABLED: false
  CONNECTION_TIMEOUT: 30
  PREFETCH_COUNT: 10
  CTF_QUEUE_NAME: ctf_tasks_queue
  CTF_OUT_QUEUE_NAME: ctf_out_tasks_queue
  MOTIONCOR_QUEUE_NAME: motioncor_tasks_queue
  MOTIONCOR_OUT_QUEUE_NAME: motioncor_out_tasks_queue

directory_settings:
  MAGELLON_HOME_DIR: C:/magellon/home
  MAGELLON_JOBS_DIR: C:/magellon/jobs
  JOBS_DIR: null
  JOBS_PROCESSING_SUB_URL: processing/
  ORIGINAL_IMAGES_SUB_URL: original/

  IMAGE_ROOT_URL: http://localhost/cdn/
  NFS_ROOT_DIR: /gpfs

  FFT_DIR: null
  FFT_SUB_URL: ffts/
  FFT_SUFFIX: _fft.png

  CTF_SUB_URL: ctf/
  FAO_SUB_URL: fao/

  GAIN_SUB_URL: gains/
  DEFECTS_SUB_URL: defects/
  FRAMES_SUB_URL: frames/
  FRAMES_SUFFIX: _frame

  IMAGES_DIR: null
  IMAGE_SUB_URL: images/


  THUMBNAILS_DIR: thumbnails/
  THUMBNAILS_SUB_URL: thumbnails/
  THUMBNAILS_SUFFIX: _thumb.png

  ATLAS_SUB_URL: atlases/
  ATLAS_SUFFIX: _atlas.png
